# create production build artifactss
FROM node:18.17.1-slim as build
WORKDIR /app/prod/
ENV PATH /app/node_modules/.bin:$PATH

#install app dependencides
COPY package*.json ./
RUN npm i
RUN npm install tsc vite -g --silent

#add the app files itself
COPY . ./
RUN npm run build

# copy the production artifacts to the nginx server folder
FROM nginx:stable-alpine
COPY --from=build /app/prod/build /usr/share/nginx/html

#expose the app port
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
